### PR TITLE
fix: support puppeteer 17

### PR DESCRIPTION
**Pull request by patrickhulce**
update to support `.frame` instead of `.executionContext`

### CODE REVIEW

**Comment by clemp6r** [comment]
It seems Puppeteer 20 works without this fix, but in order to use Puppeteer 21 we need this again.

I know this library is not longer really maintained but it would be really helpful that someone merges this.

**Comment by marcusds** [comment]
Can we get this merged to unblock us? Some services online that host tests are deprecating old version of puppeteer breaking our tests. Without this we'll have to rewrite all our tests.

**Comment by patrickhulce** [comment]
@clemp6r done

**Comment by marcusds** [comment]
@patrickhulce Are you able to also change the version number of the package and publish to NPM?

**Comment by patrickhulce** [comment]
@marcusds an automated script should have already published this, are you not seeing it?

**Comment by marcusds** [comment]
@patrickhulce I see it now, not sure why it was delayed.

Thank you so much for getting this done!

**Pull request merged**
